### ISSUE TITLE
`Gitea.clone/2` should create a local repo with the path: `./tmp/org-name/repo-name`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gitea#12]
At present we only have [`Gitea.clone/1`](https://hexdocs.pm/gitea/Gitea.html#clone/1) which clones the repo based on the `git_url` e.g:

```elixir
  org_name = "demo-org"
  repo_name = "hello-world"
  file_name = "README.md"
  # clone the remote repo:
  git_repo_url = Gitea.Helpers.remote_url_ssh(org_name, repo_name)
  local_path = Gitea.clone(git_repo_url)
  # etc.
```
That creates a directory on my localhost with the following path:
```
tmp/git@gitea-server.fly.dev:demo-org/hello-world
```
e.g:
![image](https://user-images.githubusercontent.com/194400/168998723-12cb5ff5-b2e9-4a47-bca9-8fbac840d5df.png)

This seems messy to me. 💭 
I think I would prefer: 
```sh
tmp/demo-org/hello-world
```
How about you?

**Comment by SimonLab** [comment]
I'll check again the code but I think I've created the code to have the following structure `tmp/demo-org/hello-world`
So it might be another bug or some merges not properly integrated

**Comment by SimonLab** [comment]
I did a fix on the `initialise` branch:
https://github.com/dwyl/gitea/blob/e8a8b6eaba56e803c42d8a9ca066a6339f41e6f3/lib/helpers.ex#L19-L31

That's why I thought this was working, but we need to add this change to main and this should fix your error @nelsonic

**Comment by nelsonic** [comment]
@SimonLab if you have time to PR, please do. Thanks. 👍

**Comment by SimonLab** [comment]
apply changes, run `mix test`:

Finished in 0.2 seconds (0.2s async, 0.00s sync)
4 doctests, 29 tests, 8 failures

I need to inspect the code/test to see why the tests broke with the new change

**Comment by SimonLab** [comment]
The tests were failing because we using the `get_org_repo_names` function not only for git url but also for http/s urls.
see: https://github.com/dwyl/gitea/pull/13#discussion_r875733357

**Comment by nelsonic** [comment]
Now available as: https://hexdocs.pm/gitea/1.0.1/Gitea.Helpers.html#get_org_repo_names/1 thanks @SimonLab
