### ISSUE TITLE
Feedback: Ending up on `draft` branch when I run `mix test` ...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gitea#14]
When I'm on a branch and I run the tests: `mix test`,
The tests _pass_ but I end up on the `draft` branch and there are a couple of orphan `test-repo23708085202756740` branches in my git:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/194400/169030112-14d7b48e-2038-4a7c-a069-108cbba15ff2.png">

@SimonLab do you see a similar behaviour on your `localhost`?

**Comment by SimonLab** [comment]
I had this issue when the tests were failing. Which branch was used at the start when you ran the tests, main?

**Comment by nelsonic** [comment]
Just tried this on `main` in a freshly cloned version of `gitea`:

```sh
cd /temp
git clone git@github.com:dwyl/gitea.git
cd gitea
git branch

* main
```


```sh
cp ../../path-to-valid/.env ./
source .env
mkdir tmp
mix deps.get
mix test
```

Tests pass:

```sh
Finished in 0.3 seconds (0.3s async, 0.00s sync)
6 doctests, 30 tests, 0 failures

Randomized with seed 30026
```

But ...

```sh
git branch

* draft
  test-repo33808172827731
```

in other words, running the tests switches me to the `draft` branch, _deletes_ the `main` branch and leaves an "orphan" `test-repo33808172827731` branch ... 🙄

**Comment by nelsonic** [comment]
Please LMK if you're able to replicate on your `localhost` in a freshly cloned copy of `gitea`. thanks!

**Comment by SimonLab** [comment]
Are you running the test with mock false?

**Comment by nelsonic** [comment]
```sh
n@MBP contractuali_core % cd ../temp/gitea
n@MBP gitea % cat config/test.exs
import Config
# set this to false if you want to hit the actual endpoints during development:
config :gitea, mock: System.get_env("GITHUB_WORKSPACE") || true

# Do not include metadata nor timestamps in testing logs
config :logger, :console, level: :debug, format: "[$level] $message\n"
```

`mock: true` on the freshly cloned instance of `gitea` ... i.e. what it is currently on the `main` branch:
https://github.com/dwyl/gitea/blob/25c6e487943fd775496c47bded394b2afe78e1a6/config/test.exs#L3

**Comment by nelsonic** [comment]
Yeah, this is happening while I'm trying to update the `update-docs-issue-#1` branch for https://github.com/dwyl/gitea/pull/11 and it's getting a bit frustrating. The tests all pass but my branch gets deleted and I end up on the `draft` branch ... don't know why ... I can dig through the code/tests ... but was hoping you had seen this on your end and could help.

**Comment by nelsonic** [comment]
```sh
n@MBP gitea % git branch
  main
* update-docs-issue-#1
```

```sh
mix test

.

Finished in 0.3 seconds (0.3s async, 0.00s sync)
6 doctests, 30 tests, 0 failures

Randomized with seed 745347
```

```sh
n@MBP gitea % git branch
* draft
  main
```

# 🤷‍♂️

**Comment by SimonLab** [comment]
Having lunch now, but I will have a look just after 👍

**Comment by nelsonic** [comment]
Bon Appétit. 🥖  🧀  🍷  😜

**Comment by nelsonic** [comment]
I've added some code to attempt to fix the issue:
https://github.com/dwyl/gitea/blob/eabd1f6c0e8c46f1c3108f41e7c1ddb7905d1098/test/gitea_test.exs#L122-L137

**Comment by nelsonic** [comment]
Please see: #11 👍

**Comment by nelsonic** [comment]
I think this is resolved now. Closing. ✅
