### ISSUE TITLE
Create `clone/2` where the second parameter is a path

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea#21]
We have currently `clone/1` function define as:
https://github.com/dwyl/gitea/blob/0c2bb0e2f5cdc1419a3eb4530cab857c8297b2cc/lib/gitea.ex#L149-L152

It clones the repository to the path created as `/org_name/repo_name`.
`clone/2` will allow us to specify the path to clone the repository to:

```elixir
clone(git_url, ["myorg", "myrepos", ...])
```

**Comment by nelsonic** [comment]
as in, instead of having the path be _implicit_ make it _explicit_ so that you can place the cloned repo somewhere else? 💭

**Comment by nelsonic** [comment]
The feature was published in https://hex.pm/packages/gitea/1.0.6 📦 🚀
