### ISSUE TITLE
Add Mock (Test Double) Functions to speed up Dev/Testing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gitea#28]
At present when I run the tests on the `gitea-demo` https://github.com/dwyl/gitea-demo/pull/5 they fail and have poor coverage:
![image](https://user-images.githubusercontent.com/194400/170224182-5d9503b5-f4dc-42f4-aa80-4332a80c0d41.png)

This will be the case in _any_ app that consumes the `gitea` package. 

# Todo

+ [ ] Add test double / mock functions for each of the un-tested functions

**Comment by SimonLab** [comment]
I find working with the tests difficult at the moment. We have a few issues linked to the mocks: 
- https://github.com/dwyl/gitea/pull/27#issuecomment-1137003047
- https://github.com/dwyl/gitea/issues/25#issuecomment-1136061579

And to make sure all the "path" for the return of functions are covered I need to write specific mocks. This might get more complicated when we add more features in the package.

For this specific issue, I would first remove/reduce the mock and run the tests directly on an instance of gitea. This would allow us to have the library tested again a "real" environment and to spot any errors for example if a new Gitea version break some api.
Then I would let the application using the gitea dependency (ex: gitea-demo) mock the Gitea functions used. This would allow the application to define what to do when calling Gitea function and not having it define in Gitea dependency itself.

**Comment by nelsonic** [comment]
@SimonLab to be clear: I 100% agree. I _detest_ mocks!!
Mocks are like ["fake friends"](https://www.google.com/search?q=fake+friends+meme&tbm=isch); they tell us what we _want_ to hear not the _truth_!
If it were up to me we would _never_ mock anything and would always run real-world end-to-end tests.

My _reasoning_ for having mocks in this type of HTTP/Network-dependent package is two-fold:

1. Tests pass (with coverage) on GitHub CI where we haven't been able to setup the SSH key (on CI) to `git clone` or `git push` to the Gitea Server.
2. Let the downstream module where we (_or other devs using the `gitea` package_) might not _want_ to hit the _actual_ server endpoints during tests/CI both because of time (tests taking much longer to run) or just being ***offline*** ...

Again, I **100% agree** with running the tests with **`mock: false`** I do this on `localhost`. ✅ 
But in the **`demo`** app and _other_ "consumer" apps, I don't see much choice. Do you? 🤷‍♂️ 

If there is a way around this, we should _totally_ explore it. 🔍

**Comment by nelsonic** [comment]
cheekily included in #36 🙊

**Comment by nelsonic** [comment]
Tests now pass in the demo (`mock: true`) with 100% coverage on CI: https://github.com/dwyl/gitea-demo/pull/5
![image](https://user-images.githubusercontent.com/194400/170660391-92631c37-0b60-4d41-806c-276b7569c5d3.png)

Again, I _detest_ Mocks. But if it means my tests run faster on `localhost` and _pass_ on CI ... then `#NecessaryEvil`. 🙄
