### ISSUE TITLE
Define `git_dir` at runtime isntead of compile time

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea#30]
https://github.com/dwyl/gitea/blob/e7bdb1a0ebee4e829a15d6cdb80d8011021895bc/lib/helpers.ex#L10

The @git_dir is defined using environment variable `GIT_TEMP_DIR_PATH`. This value needs to be available at compile time otherwise Gitea uses the current working directory.

I had an issue where my repositories weren't cloned where I was thinking. My environment variable wasn't defined and the repositories were created in the deps folder: `/deps/gitea/myrepo`. Even after adding the environment variable the repositories where still added to the deps folder.

This is because [module attributes](https://elixir-lang.org/getting-started/module-attributes.html#as-constants) are evaluated at compile time.
>if you are reading a value from a database or an environment variable inside an attribute, be aware that it will read that value only at compilation time

So I would have to recompile the Gitea dependency to have the value updated based on my new environment variable.

I think it is safer to create a function which will be evaluated at runtime instead of using a module attribute.

**Comment by nelsonic** [comment]
@SimonLab agree that this could be useful to some people. But how often do you find yourself updating the `git_dir`? 💭

**Comment by SimonLab** [comment]
Once the application using Gitea is running I agree that I can't see the value changing. However the value need to be defined first before compilation.
The other use case is while creating the application using Gitea dependency, I change the value often but I don't want to recompile the dependency each time I do a change

**Comment by nelsonic** [comment]
hmm ... if you feel that you are changing it "often", then fair enough, make the necessary changes. 👍

**Comment by nelsonic** [comment]
Code included in PR #31 and package published to https://hex.pm/packages/gitea/1.0.8 :shipit:
