### ISSUE TITLE
Handle `Git.add` and `Git.commit` errors in `commit/3`

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea#32]
https://github.com/dwyl/gitea/blob/9a69306926bdc7656653ec432acced0b475a1fdf/lib/gitea.ex#L265-L277

We are only checking the `{:ok, _}`  values when matching with with `Git.add` and `Git.commit` functions.
If one of these functions fail, the main function will crash.

I'll update the function to take care of the possible errors

**Comment by nelsonic** [comment]
@SimonLab definitely! Error handling is a _must_. We cannot assume the path will always be happy. ⛈️ 
Thanks! 🙌

**Comment by nelsonic** [comment]
Code added by @SimonLab  in #33 and package published to https://hex.pm/packages/gitea/1.0.9 :shipit:
