### ISSUE TITLE
Create local branch without switching to it

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea#34]
https://github.com/dwyl/gitea/blob/171573c4b9571a005ad626a73aa31100c1e63e19/lib/gitea.ex#L206-L222

The `local_branch_create` creates the branch and currently switch to it (using git checkout -b).
I'd like to be able to split this steps and have one function to just create a branch (`git branch name-branch`) and a function to switch to a branch (`git switch name-branch`).

I can either update the existing `local_branch_create` to use `branch` instead of `checkout` or I can create `create_branch` and `switch_branch` functions. @nelsonic do you have any preferences?

**Comment by nelsonic** [comment]
@SimonLab this is a totally valid use case. 👌 
I wrote this function this way as it was the most _likely_ use case we would be using. 💭 
Happy for you to update/re-work as you see fit. 
Please document, test and create PR. 
Thanks!

**Comment by nelsonic** [comment]
**P.S**: perhaps take a quick look at #29 _first_ ... 💭

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/gitea/1.1.11
