### ISSUE TITLE
Test failing for `temp_dir` function

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea#39]
![image](https://user-images.githubusercontent.com/6057298/170683744-76867a3b-9e23-4c37-9cde-45318b7c3d42.png)

- [ ] Review test and how the temp_dir functions works to fix this failing test

**Comment by nelsonic** [comment]
Still an issue after https://github.com/dwyl/gitea/pull/40 ...? 💭

**Comment by SimonLab** [comment]
No this is fixed now, thanks for the review on #40
