### ISSUE TITLE
API doc

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea#5]
The api documentation can be found at: https://gitea-server.fly.dev/api/swagger:

![image](https://user-images.githubusercontent.com/6057298/168616648-eccafe71-fea1-48ad-a7c0-99294a796b4b.png)

**Comment by nelsonic** [comment]
Yeah, this is a _far_ better DevEx than having to lookup the docs on a separate GitHub repo ... 👍 
Glad we made the switch. 🩹

**Comment by nelsonic** [comment]
PR: #42 merged. ✅ 
(thanks @SimonLab)
