### ISSUE TITLE
Using ssh key with Github CI

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea#6]
The following part of the github action create the configuration to allow the workflow to use ssh key:

```yml
    - name: Create SSH key
      run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H gitea-server.fly.dev > ~/.ssh/known_hosts
```

You need first to create ssh key and then copy the private key to the Github SSH_PRIVATE_KEY repository value

see: https://stackoverflow.com/questions/60477061/github-actions-how-to-deploy-to-remote-server-using-ssh

**Comment by SimonLab** [comment]
I've tested adding a private ssh key to the Github action to allow the CI to use git and it worked with this step:
https://github.com/dwyl/gitea/blob/e8a8b6eaba56e803c42d8a9ca066a6339f41e6f3/.github/workflows/ci.yml#L35-L39

Closing for now as we are using mock

**Comment by nelsonic** [comment]
Still super keen to get this working though. Would prefer to have _real_ end-to-end tests over mocks any day!
