### ISSUE TITLE
Feat: Create Org

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gitea#7]
One of the reasons we switched from `Gogs` to `Gitea` was the **`Org`** creation endpoint:  `POST /orgs` > https://try.gitea.io/api/swagger#/organization/orgCreate
![image](https://user-images.githubusercontent.com/194400/168423928-0051ff45-49f0-4887-9a77-08443991b4f5.png)

# Todo

+ [x] create a function that accepts the necessary params:
```json
{
  "description": "Org description if applicable",
  "full_name":  "Long Name (e.g. Full Legal Name)",
  "username": "orgname-all-lowercase-no-spaces",
  "visibility": "hidden"
}
```
+ [x] Use the function to create an `Org`!

**Comment by SimonLab** [comment]
Implemented with https://github.com/dwyl/gitea/pull/8
